 /*****************************************************************
 *                                                                *
 * Copyright (C) 2017-2018 Oliver Welter <contact@verbotene.zone> *
 *                                                                *
 * This is free software, for non-commercial use, licensed under  *
 * The Non-Profit Open Software License version 3.0 (NPOSL-3.0).  *
 *                                                                *
 * See /LICENSE for more information.                             *
 *                                                                *
 *****************************************************************/

#ifndef defines_h
#define defines_h

#ifndef WITH_TARGET_ARDUINO
#define _USE_MATH_DEFINES 
#include <math.h>
#include <time.h>
#include <inttypes.h>
#define byte uint8_t
#define boolean bool
#define false 0
#define true 1
#ifndef PI
#define PI 3.14159265358979323846f
#endif 
#define millis() { time(0)*1000 }
#define B00000001 0x01
#define B00000010 0x02
#define B00000100 0x04
#define B00001000 0x08
#define B00010000 0x10
#define B00100000 0x20
#define B01000000 0x40
#define B10000000 0x80
#define B00001111 0x0f
#define B11110000 0xf0
#endif

#ifndef INT32U
#define INT32U unsigned long
#endif

#ifndef INT8U
#define INT8U byte
#endif

#define BMWXCAN_CMP_OK										0x00
#ifdef WITH_IGNORED_IDS
#define BMWXCAN_CMP_IGNORED_ID									0xf1
#endif
#ifdef WITH_UNKNOWN_IDS
#define BMWXCAN_CMP_UNKNOWN_ID									0xf2
#endif
#define BMWXCAN_CMP_INVALID_LENGTH								0xf3
#define BMWXCAN_CMP_IMMIDIATE_EXIT								0xfe
#define BMWXCAN_CMP_UNREGISTERED_ID								0xff

#define BMWXCAN_CAN_ID_THROTTLE_AND_RPM_F							0x0A5
#define BMWXCAN_CAN_ID_TORQUE_CLUTCH_BRAKE 							0x0A8
#define BMWXCAN_CAN_ID_RPM_AND_THROTTLE_POSITION							0x0AA
#define BMWXCAN_CAN_ID_ALIVE_COUNTER								0x0BE
#define BMWXCAN_CAN_ID_ABS_BRAKE_COUNTER								0x0C0
#define BMWXCAN_CAN_ID_STEERING_WHEEL_POS_A							0x0C4
#define BMWXCAN_CAN_ID_STEERING_WHEEL_POS_B							0x0C5
#define BMWXCAN_CAN_ID_INDIVIDUAL_WHEEL_SPEED							0x0CE
#define BMWXCAN_CAN_ID_AIRBAG_SEATBELT_COUNTER							0x0D7
#define BMWXCAN_CAN_ID_DOOR_STATUS_FRONT_PASSENGER						0x0E2
#define BMWXCAN_CAN_ID_DOOR_STATUS_REAR_PASSENGER						0x0E6
#define BMWXCAN_CAN_ID_DOOR_STATUS_FRONT_DRIVER							0x0EA
#define BMWXCAN_CAN_ID_DOOR_STATUS_REAR_DRIVER							0x0EE
#define BMWXCAN_CAN_ID_BOOT_STATUS								0x0F2
#define BMWXCAN_CAN_ID_WINDOW_LIFTER_CONTROL_FRONT_DRIVER					0x0FA
#define BMWXCAN_CAN_ID_WINDOW_LIFTER_CONTROL_FRONT_PASSENGER					0x0FB
#define BMWXCAN_CAN_ID_WINDOW_LIFTER_CONTROL_REAR_DRIVER						0x0FC
#define BMWXCAN_CAN_ID_WINDOW_LIFTER_CONTROL_REAR_PASSENGER					0x0FD
#define BMWXCAN_CAN_ID_IGNITION_STATUS								0x130
#define BMWXCAN_CAN_ID_TIMER_AND_CRUISE_CONTROL_STATUS						0x193
#define BMWXCAN_CAN_ID_ABS_BRAKE									0x19E
#define BMWXCAN_CAN_ID_SPEED									0x1A6
#define BMWXCAN_CAN_ID_SPEED_HANDBRAKE								0x1B4
#define BMWXCAN_CAN_ID_I_DRIVE_CONTROL								0x1B8 // C0 0C for clearance is not yet proven, therefore a millis timer has been implemented
#define BMWXCAN_CAN_ID_PDC_SENSOR_DATA								0x1C2
#define BMWXCAN_CAN_ID_PDC_BUTTON								0x1C6
#define BMWXCAN_CAN_ID_ENGINE_TEMP_AND_PRESSURE							0x1D0 // OIL TEMP NOT YET PROVEN - POSSIBLY COOLANT LEVEL AND OTHER PRESSURES
#define BMWXCAN_CAN_ID_STEERING_WHEEL_BUTTONS							0x1D6
#define BMWXCAN_CAN_ID_INTERIOR_LIGHT_SWITCH							0x1E3
#define BMWXCAN_CAN_ID_SEAT_HEATING_DRIVER							0x1E7 // UNSTABLE! Values not yet known, therefore raw data is stored
#define BMWXCAN_CAN_ID_SEAT_HEATING_PASSENGER							0x1E8 // UNSTABLE! Values not yet known, therefore raw data is stored
#define BMWXCAN_CAN_ID_ADJUST_STEERING_WHEEL							0x1EA
#define BMWXCAN_CAN_ID_INDICATOR_STALK								0x1EE
#define BMWXCAN_CAN_ID_SEAT_ADJUSTMENT_DRIVER							0x1F3
#define BMWXCAN_CAN_ID_INDICATORS								0x1F6
#define BMWXCAN_CAN_ID_CRASH									0x1FE
#define BMWXCAN_CAN_ID_CRUISE_CONTROL_SPEED_STEP							0x200 // UNSTABLE! Not sure if payload[1] holds speed
#define BMWXCAN_CAN_ID_INSTRUMENTS_DIMMER							0x202
#define BMWXCAN_CAN_ID_LIGHTS_SWITCH								0x21A
#define BMWXCAN_CAN_ID_CARKEY_BUTTON								0x23A
#define BMWXCAN_CAN_ID_AIRCONDITION								0x242
#define BMWXCAN_CAN_ID_AIRCONDITION_DEMISTER							0x246
#define BMWXCAN_CAN_ID_PDC									0x24A
#define BMWXCAN_CAN_ID_WINDSCREEN_WIPER_STATUS							0x252
#define BMWXCAN_CAN_ID_I_DRIVEH_CONTROLLER_ROTARY_CONTROL					0x264 // I DRIVE HIGH
#define BMWXCAN_CAN_ID_I_DRIVEH_CONTROLLER_DIRECTION_BUTTONS					0x267 // I DRIVE HIGH
#define BMWXCAN_CAN_ID_RADIO_STATUS								0x273
#define BMWXCAN_CAN_ID_I_DRIVEH_CONTROLLER_REPLY							0x277 // POSSIBLE REPLY TO RADIO_STATUS - IGNORED
#define BMWXCAN_CAN_ID_REAR_VIEW_MIRROR_LIGHT_SENSOR						0x286
#define BMWXCAN_CAN_ID_WIPER_STALK								0x2A6
#define BMWXCAN_CAN_ID_STOP_WATCH								0x2BA
#define BMWXCAN_CAN_ID_DOOR_LOCKING_VALIDATION							0x2B4
#define BMWXCAN_CAN_ID_BC_RESET_AVERAGE_SPEED_MPG						0x2B8
#define BMWXCAN_CAN_ID_OUTSIDE_TEMPERATURE							0x2CA
#define BMWXCAN_CAN_ID_STATUS_REAR_WINDOW_HEATING						0x2D5 // 0xFC in payload[0] could by OFF - check this
#define BMWXCAN_CAN_ID_AIRCONDITION_STATUS							0x2D6
#define BMWXCAN_CAN_ID_AIRCONDITION_DRIVER							0x2E6
#define BMWXCAN_CAN_ID_AIRCONDITION_PASSENGER							0x2EA
#define BMWXCAN_CAN_ID_INSIDE_LIGHTS								0x2F6
#define BMWXCAN_CAN_ID_DATE_TIME									0x2F8
#define BMWXCAN_CAN_ID_SEATBELT_SENSORS								0x2FA // We assume, 0xFC stands for seatbelt contact open
#define BMWXCAN_CAN_ID_DOOR_BOOT_BONNET_STATUS							0x2FC
#define BMWXCAN_CAN_ID_GEAR_LEVER								0x304 // R, D IDs may be wrong - also check DS and Mx
#define BMWXCAN_CAN_ID_CAR_TILT									0x306
#define BMWXCAN_CAN_ID_STATUS_TIRE_SPAN_DISPLAY							0x31D
#define BMWXCAN_CAN_ID_SECONDS_SINCE_BAT_REMOVAL							0x328
#define BMWXCAN_CAN_ID_INSIDE_TEMP_LIGHT_SOLAR_SENSORS						0x32E
#define BMWXCAN_CAN_ID_MILEAGE_RANGE_TANK_LEVEL							0x330
#define BMWXCAN_CAN_ID_CHECKCONTROL_MESSAGE_MIL							0x336
#define BMWXCAN_CAN_ID_CHECKCONTROL_MESSAGE_DSC							0x338
#define BMWXCAN_CAN_ID_FUEL_LEVEL_SENSORS							0x349
#define BMWXCAN_CAN_ID_STATUS_HANDBRAKE								0x34F
#define BMWXCAN_CAN_ID_AVERAGE_SPEED_AND_MILEAGE							0x362
#define BMWXCAN_CAN_ID_VIN									0x380
#define BMWXCAN_CAN_ID_STATUS_BATTERY_AND_ENGINE							0x3B4
#define BMWXCAN_CAN_ID_POSITION_WINDOW_FRONT_PASSENGER						0x3B6
#define BMWXCAN_CAN_ID_POSITION_WINDOW_REAR_DRIVER						0x3B7
#define BMWXCAN_CAN_ID_POSITION_WINDOW_FRONT_DRIVER						0x3B8
#define BMWXCAN_CAN_ID_POSITION_WINDOW_REAR_PASSENGER						0x3B9
#define BMWXCAN_CAN_ID_POSITION_ROOF								0x3BA
#define BMWXCAN_CAN_ID_FASTEN_SEATBELT_SIGN							0x581
#define BMWXCAN_CAN_ID_CONTROL_SUN_ROLLERS							0x26C
#ifdef WITH_IGNORED_IDS
#define BMWXCAN_CAN_ID_SPEED_K_CAN								0x1A0 // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_SPEED_K_CAN_2								0x1A1 // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_WARMTH_CLIMATE								0x1B5 // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_WARMTH_MOTOR								0x1B6 // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_DISPLAY_GEARING_DATA							0x1D2 // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_COUNTER_AND_DOOR_STATUS							0x1E1 // CURRENTLY IGNORED DUE TO 0Ex DOOR STATUS - msg repeat 200ms
#define BMWXCAN_CAN_ID_STATUS_AFS								0x1FC // CURRENTLY IGNORED - Dont know how to translate the values
#define BMWXCAN_CAN_ID_RAINSENSOR_WIPESPEED							0x226 // CURRENTLY IGNORED - Dont know how to translate the values
#define BMWXCAN_CAN_ID_STATUS_BFS								0x22A // CURRENTLY IGNORED - Dont know how to translate the values
#define BMWXCAN_CAN_ID_STATUS_FAS								0x232 // CURRENTLY IGNORED - Dont know how to translate the values
#define BMWXCAN_CAN_ID_CONTROL_ROOF								0x26E // CURRENTLY IGNORED - HANDLING NOT TESTED
#define BMWXCAN_CAN_ID_DOOR_STATUS_IGN								0x24B // IGNORED DUE TO 2FC
#define BMWXCAN_CAN_ID_CONTROL_CENTRAL_LOCKING							0x2A0 // CURRENTLY IGNORED - HANDLING NOT TESTED
#define BMWXCAN_CAN_ID_LCD_BRIGHTNESS								0x2C0 // CURRENTLY IGNORED - Dont know how to handle the 3 bytes
#define BMWXCAN_CAN_ID_CONTROL_MONITOR								0x2CE // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_STATUS_CLIMATE_STANDOPS							0x2F0 // CURRENTLY IGNORED - HANDLING UNKNOWN
#define BMWXCAN_CAN_ID_CONTROL_EXTEN_WATERPUMP							0x2F4 // CURRENTLY IGNORED - HANDLING UNKNOWN
#define BMWXCAN_CAN_ID_UNITS									0x2F7 // CURRENTLY IGNORED - HANDLING UNKNOWN
#define BMWXCAN_CAN_ID_STATUS_SERVICE_CALL							0x313 // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_STATUS_DRIVING_LIGHTS							0x314 // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_VEHICLE_MODE								0x315 // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_CONTROL_ALC								0x32A // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_DRIVER_DISPLAY_ROTATIONAREA						0x332 // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_STATUS_FUEL_PUMP								0x335 // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_STATUS_MONITOR_FRONT							0x33A // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_BORDCOMPUTER_DATA								0x35C // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_BORDCOMPUTER_TRAVEL_DATA							0x35E // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_BORDCOMPUTER_START_DATA							0x360 // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_BORDCOMPUTER_INFO_DATA							0x364 // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_OUTSIDE_TEMP_AND_RANGE							0x366 // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_CONTROL_DISPLAY_SERVICEREQ						0x367 // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_RDA_REQUEST_DATASTORE							0x394 // CURRENTLY IGNORE
#define BMWXCAN_CAN_ID_SET_TIME_AND_DATE								0x39E // CURRENTLY IGNORE
#define BMWXCAN_CAN_ID_STATUS_REVERSE								0x3B0 // CURRENTLY IGNORE
#define BMWXCAN_CAN_ID_POWERMANAGEMENT_CONTROL							0x3B3 // CURRENTLY IGNORE
#define BMWXCAN_CAN_ID_STATUS_CONSUMER_SHUTDOWN							0x3BD // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_POST_TIME_POWER_SUPPLY							0x3BE // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_STATUS_MEMORYPOS_CKM							0x3DB // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_STATUS_LIGHT_CKM								0x3DD // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_STATUS_CLIMATE_CKM							0x3DF // CURRENTLY IGNORED
#define BMWXCAN_CAN_ID_KEYFOB									0x73C // CURRENTLY IGNORED
#endif
#ifdef WITH_UNKNOWN_IDS
#define BMWXCAN_CAN_ID_UNKNOWN_1									0x174
#define BMWXCAN_CAN_ID_UNKNOWN_2									0x480
#define BMWXCAN_CAN_ID_UNKNOWN_3									0x4C0
#define BMWXCAN_CAN_ID_UNKNOWN_4									0x4C3
#define BMWXCAN_CAN_ID_UNKNOWN_5									0x4C4
#define BMWXCAN_CAN_ID_UNKNOWN_6									0x4C5
#define BMWXCAN_CAN_ID_UNKNOWN_7									0x4E0
#define BMWXCAN_CAN_ID_UNKNOWN_8									0x4E2
#define BMWXCAN_CAN_ID_UNKNOWN_9									0x4E4
#define BMWXCAN_CAN_ID_UNKNOWN_10								0x4E5
#define BMWXCAN_CAN_ID_UNKNOWN_11								0x4E7
#define BMWXCAN_CAN_ID_UNKNOWN_12								0x4ED
#define BMWXCAN_CAN_ID_UNKNOWN_13								0x4EE
#define BMWXCAN_CAN_ID_UNKNOWN_14								0x4F0
#define BMWXCAN_CAN_ID_UNKNOWN_15								0x4F2
#define BMWXCAN_CAN_ID_UNKNOWN_16								0x4F3
#define BMWXCAN_CAN_ID_UNKNOWN_17								0x4F8
#define BMWXCAN_CAN_ID_UNKNOWN_18								0x580
#define BMWXCAN_CAN_ID_UNKNOWN_19								0x592
#define BMWXCAN_CAN_ID_UNKNOWN_20								0x596
#define BMWXCAN_CAN_ID_UNKNOWN_21								0x5A3
#define BMWXCAN_CAN_ID_UNKNOWN_22								0x5A9
#define BMWXCAN_CAN_ID_UNKNOWN_23								0x5C0
#define BMWXCAN_CAN_ID_UNKNOWN_24								0x5E0
#define BMWXCAN_CAN_ID_UNKNOWN_25								0x5E2
#define BMWXCAN_CAN_ID_UNKNOWN_26								0x5E7
#define BMWXCAN_CAN_ID_UNKNOWN_27								0x5ED
#define BMWXCAN_CAN_ID_UNKNOWN_28								0x5EE
#define BMWXCAN_CAN_ID_UNKNOWN_29								0x5F3
#define BMWXCAN_CAN_ID_UNKNOWN_30								0x5F8
#define BMWXCAN_CAN_ID_UNKNOWN_31								0x172
#define BMWXCAN_CAN_ID_UNKNOWN_33								0x1AA
#define BMWXCAN_CAN_ID_UNKNOWN_37								0x205
#define BMWXCAN_CAN_ID_UNKNOWN_38								0x226
#define BMWXCAN_CAN_ID_UNKNOWN_45								0x2F7
#define BMWXCAN_CAN_ID_UNKNOWN_58								0x388
#define BMWXCAN_CAN_ID_UNKNOWN_60								0x395
#define BMWXCAN_CAN_ID_UNKNOWN_61								0x398
#define BMWXCAN_CAN_ID_UNKNOWN_63								0x3B5
#define BMWXCAN_CAN_ID_UNKNOWN_69								0x4B8
#define BMWXCAN_CAN_ID_UNKNOWN_70								0x5B8
#define BMWXCAN_CAN_ID_UNKNOWN_71								0x5C4
#define BMWXCAN_CAN_ID_UNKNOWN_72								0x5F0
#define BMWXCAN_CAN_ID_UNKNOWN_73								0x5F2
#define BMWXCAN_CAN_ID_UNKNOWN_74								0x663
#define BMWXCAN_CAN_ID_UNKNOWN_75								0x691
#define BMWXCAN_CAN_ID_UNKNOWN_76								0x698
#define BMWXCAN_CAN_ID_UNKNOWN_77								0x0C8
#endif

#define BMWXCAN_MSG_LENGTH_THROTTLE_AND_RPM_F							8
#define BMWXCAN_MSG_LENGTH_TORQUE_CLUTCH_BRAKE							8
#define BMWXCAN_MSG_LENGTH_RPM_AND_THROTTLE_POSITION						8
#define BMWXCAN_MSG_LENGTH_ALIVE_COUNTER								5
#define BMWXCAN_MSG_LENGTH_ABS_BRAKE_COUNTER							2
#define BMWXCAN_MSG_LENGTH_STEERING_WHEEL_POS_A							7
#define BMWXCAN_MSG_LENGTH_STEERING_WHEEL_POS_B							6
#define BMWXCAN_MSG_LENGTH_INDIVIDUAL_WHEEL_SPEED						8
#define BMWXCAN_MSG_LENGTH_AIRBAG_SEATBELT_COUNTER						2
#define BMWXCAN_MSG_LENGTH_DOOR_STATUS_FRONT_PASSENGER						8
#define BMWXCAN_MSG_LENGTH_DOOR_STATUS_REAR_PASSENGER						8
#define BMWXCAN_MSG_LENGTH_DOOR_STATUS_FRONT_DRIVER						8
#define BMWXCAN_MSG_LENGTH_DOOR_STATUS_REAR_DRIVER						8
#define BMWXCAN_MSG_LENGTH_BOOT_STATUS								8
#define BMWXCAN_MSG_LENGTH_WINDOW_LIFTER_CONTROL_FRONT_DRIVER					3
#define BMWXCAN_MSG_LENGTH_WINDOW_LIFTER_CONTROL_FRONT_PASSENGER					3
#define BMWXCAN_MSG_LENGTH_WINDOW_LIFTER_CONTROL_REAR_DRIVER					3
#define BMWXCAN_MSG_LENGTH_WINDOW_LIFTER_CONTROL_REAR_PASSENGER					3
#define BMWXCAN_MSG_LENGTH_IGNITION_STATUS							5
#define BMWXCAN_MSG_LENGTH_UNKNOWN								8
#define BMWXCAN_MSG_LENGTH_TIMER_AND_CRUISE_CONTROL_STATUS					8
#define BMWXCAN_MSG_LENGTH_ABS_BRAKE								8
#define BMWXCAN_MSG_LENGTH_SPEED_K_CAN								8
#define BMWXCAN_MSG_LENGTH_SPEED_K_CAN_2								5
#define BMWXCAN_MSG_LENGTH_SPEED									8
#define BMWXCAN_MSG_LENGTH_SPEED_HANDBRAKE							8
#define BMWXCAN_MSG_LENGTH_WARMTH_CLIMATE							6
#define BMWXCAN_MSG_LENGTH_WARMTH_MOTOR								7
#define BMWXCAN_MSG_LENGTH_I_DRIVE_CONTROL							6
#define BMWXCAN_MSG_LENGTH_PDC_SENSOR_DATA							8
#define BMWXCAN_MSG_LENGTH_PDC_BUTTON								4
#define BMWXCAN_MSG_LENGTH_ENGINE_TEMP_AND_PRESSURE						8
#define BMWXCAN_MSG_LENGTH_DISPLAY_GEARING_DATA							6
#define BMWXCAN_MSG_LENGTH_STEERING_WHEEL_BUTTONS						2
#define BMWXCAN_MSG_LENGTH_COUNTER_AND_DOOR_STATUS						6
#define BMWXCAN_MSG_LENGTH_INTERIOR_LIGHT_SWITCH							2
#define BMWXCAN_MSG_LENGTH_SEAT_HEATING_DRIVER							2
#define BMWXCAN_MSG_LENGTH_SEAT_HEATING_PASSENGER						2
#define BMWXCAN_MSG_LENGTH_ADJUST_STEERING_WHEEL							2
#define BMWXCAN_MSG_LENGTH_INDICATOR_STALK							2
#define BMWXCAN_MSG_LENGTH_SEAT_ADJUSTMENT_DRIVER						2
#define BMWXCAN_MSG_LENGTH_INDICATORS								2
#define BMWXCAN_MSG_LENGTH_STATUS_AFS								2
#define BMWXCAN_MSG_LENGTH_CRASH									2
#define BMWXCAN_MSG_LENGTH_CRUISE_CONTROL_SPEED_STEP						8
#define BMWXCAN_MSG_LENGTH_INSTRUMENTS_DIMMER							2
#define BMWXCAN_MSG_LENGTH_LIGHTS_SWITCH								3
#define BMWXCAN_MSG_LENGTH_RAINSENSOR_WIPESPEED							5 // Or possibly 2 - check this first before doing something with the values
#define BMWXCAN_MSG_LENGTH_STATUS_BFS								3
#define BMWXCAN_MSG_LENGTH_STATUS_FAS								3
#define BMWXCAN_MSG_LENGTH_CARKEY_BUTTON								4
#define BMWXCAN_MSG_LENGTH_AIRCONDITION								3
#define BMWXCAN_MSG_LENGTH_AIRCONDITION_DEMISTER							5
#define BMWXCAN_MSG_LENGTH_PDC									2
#define BMWXCAN_MSG_LENGTH_DOOR_STATUS_IGN							2
#define BMWXCAN_MSG_LENGTH_WINDSCREEN_WIPER_STATUS						2
#define BMWXCAN_MSG_LENGTH_I_DRIVEH_CONTROLLER_ROTARY_CONTROL					6
#define BMWXCAN_MSG_LENGTH_I_DRIVEH_CONTROLLER_DIRECTION_BUTTONS					6
#define BMWXCAN_MSG_LENGTH_CONTROL_SUN_ROLLERS							3
#define BMWXCAN_MSG_LENGTH_CONTROL_ROOF								8
#define BMWXCAN_MSG_LENGTH_RADIO_STATUS								8
#define BMWXCAN_MSG_LENGTH_I_DRIVEH_CONTROLLER_REPLY						4
#define BMWXCAN_MSG_LENGTH_REAR_VIEW_MIRROR_LIGHT_SENSOR						2
#define BMWXCAN_MSG_LENGTH_CONTROL_CENTRAL_LOCKING						8
#define BMWXCAN_MSG_LENGTH_WIPER_STALK								2
#define BMWXCAN_MSG_LENGTH_STOP_WATCH								5
#define BMWXCAN_MSG_LENGTH_DOOR_LOCKING_VALIDATION						2
#define BMWXCAN_MSG_LENGTH_BC_RESET_AVERAGE_SPEED_MPG						6
#define BMWXCAN_MSG_LENGTH_LCD_BRIGHTNESS							3
#define BMWXCAN_MSG_LENGTH_OUTSIDE_TEMPERATURE							2
#define BMWXCAN_MSG_LENGTH_CONTROL_MONITOR							3
#define BMWXCAN_MSG_LENGTH_STATUS_REAR_WINDOW_HEATING						2
#define BMWXCAN_MSG_LENGTH_AIRCONDITION_STATUS							3
#define BMWXCAN_MSG_LENGTH_AIRCONDITION_DRIVER							8
#define BMWXCAN_MSG_LENGTH_AIRCONDITION_PASSENGER						8
#define BMWXCAN_MSG_LENGTH_STATUS_CLIMATE_STANDOPS						2
#define BMWXCAN_MSG_LENGTH_CONTROL_EXTEN_WATERPUMP						4
#define BMWXCAN_MSG_LENGTH_INSIDE_LIGHTS								2
#define BMWXCAN_MSG_LENGTH_UNITS									4
#define BMWXCAN_MSG_LENGTH_DATE_TIME								8
#define BMWXCAN_MSG_LENGTH_SEATBELT_SENSORS							5
#define BMWXCAN_MSG_LENGTH_DOOR_BOOT_BONNET_STATUS						7
#define BMWXCAN_MSG_LENGTH_GEAR_LEVER								2
#define BMWXCAN_MSG_LENGTH_CAR_TILT								2
#define BMWXCAN_MSG_LENGTH_STATUS_SERVICE_CALL							2
#define BMWXCAN_MSG_LENGTH_STATUS_DRIVING_LIGHTS							3
#define BMWXCAN_MSG_LENGTH_VEHICLE_MODE								2
#define BMWXCAN_MSG_LENGTH_STATUS_TIRE_SPAN_DISPLAY						2
#define BMWXCAN_MSG_LENGTH_SECONDS_SINCE_BAT_REMOVAL						6
#define BMWXCAN_MSG_LENGTH_CONTROL_ALC								2
#define BMWXCAN_MSG_LENGTH_INSIDE_TEMP_LIGHT_SOLAR_SENSORS					8
#define BMWXCAN_MSG_LENGTH_MILEAGE_RANGE_TANK_LEVEL						8
#define BMWXCAN_MSG_LENGTH_DRIVER_DISPLAY_ROTATIONAREA						2
#define BMWXCAN_MSG_LENGTH_STATUS_FUEL_PUMP							8
#define BMWXCAN_MSG_LENGTH_CHECKCONTROL_MESSAGE_MIL						7
#define BMWXCAN_MSG_LENGTH_CHECKCONTROL_MESSAGE_DSC						8
#define BMWXCAN_MSG_LENGTH_STATUS_MONITOR_FRONT							5
#define BMWXCAN_MSG_LENGTH_FUEL_LEVEL_SENSORS							5
#define BMWXCAN_MSG_LENGTH_STATUS_HANDBRAKE							2
#define BMWXCAN_MSG_LENGTH_BORDCOMPUTER_DATA							4
#define BMWXCAN_MSG_LENGTH_BORDCOMPUTER_TRAVEL_DATA						8
#define BMWXCAN_MSG_LENGTH_BORDCOMPUTER_START_DATA						7
#define BMWXCAN_MSG_LENGTH_AVERAGE_SPEED_AND_MILEAGE						7
#define BMWXCAN_MSG_LENGTH_BORDCOMPUTER_INFO_DATA						7
#define BMWXCAN_MSG_LENGTH_OUTSIDE_TEMP_AND_RANGE						4
#define BMWXCAN_MSG_LENGTH_CONTROL_DISPLAY_SERVICEREQ 						7
#define BMWXCAN_MSG_LENGTH_VIN									7
#define BMWXCAN_MSG_LENGTH_RDA_REQUEST_DATASTORE							8
#define BMWXCAN_MSG_LENGTH_SET_TIME_AND_DATE							8
#define BMWXCAN_MSG_LENGTH_STATUS_REVERSE							2
#define BMWXCAN_MSG_LENGTH_POWERMANAGEMENT_CONTROL						6
#define BMWXCAN_MSG_LENGTH_STATUS_BATTERY_AND_ENGINE						8
#define BMWXCAN_MSG_LENGTH_POSITION_WINDOW_FRONT_DRIVER						2
#define BMWXCAN_MSG_LENGTH_POSITION_WINDOW_REAR_DRIVER						2
#define BMWXCAN_MSG_LENGTH_POSITION_WINDOW_FRONT_PASSENGER					2
#define BMWXCAN_MSG_LENGTH_POSITION_WINDOW_REAR_PASSENGER	 				2
#define BMWXCAN_MSG_LENGTH_POSITION_ROOF								7
#define BMWXCAN_MSG_LENGTH_STATUS_CONSUMER_SHUTDOWN						2
#define BMWXCAN_MSG_LENGTH_POST_TIME_POWER_SUPPLY						2
#define BMWXCAN_MSG_LENGTH_STATUS_MEMORYPOS_CKM							2
#define BMWXCAN_MSG_LENGTH_STATUS_LIGHT_CKM							3
#define BMWXCAN_MSG_LENGTH_STATUS_CLIMATE_CKM							3
#define BMWXCAN_MSG_LENGTH_FASTEN_SEATBELT_SIGN							8
#define BMWXCAN_MSG_LENGTH_KEYFOB								8
#endif
